package StudentManageApp;

import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hasan
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        setTitle("Student Management System");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        setSize(850, 550);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftMenu = new javax.swing.JPanel();
        StdManage = new javax.swing.JButton();
        CourseManage = new javax.swing.JButton();
        GradeManage = new javax.swing.JButton();
        HomeTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");

        leftMenu.setBackground(new java.awt.Color(51, 51, 51));

        StdManage.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        StdManage.setText("Student Management Panel");
        StdManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdManageActionPerformed(evt);
            }
        });

        CourseManage.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        CourseManage.setText("Course Enrollment Panel");
        CourseManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseManageActionPerformed(evt);
            }
        });

        GradeManage.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        GradeManage.setText("Grade Management Panel");
        GradeManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeManageActionPerformed(evt);
            }
        });

        HomeTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        HomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        HomeTitle.setText("Welcome to Student Management System");

        javax.swing.GroupLayout leftMenuLayout = new javax.swing.GroupLayout(leftMenu);
        leftMenu.setLayout(leftMenuLayout);
        leftMenuLayout.setHorizontalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftMenuLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftMenuLayout.createSequentialGroup()
                        .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GradeManage, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CourseManage, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StdManage, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftMenuLayout.createSequentialGroup()
                        .addComponent(HomeTitle)
                        .addGap(192, 192, 192))))
        );
        leftMenuLayout.setVerticalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(StdManage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(CourseManage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(GradeManage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StdManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdManageActionPerformed
        StudentManagementPanel smp = new StudentManagementPanel();
        smp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StdManageActionPerformed

    private void CourseManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseManageActionPerformed

        Map<String, String> studentmap = StudentManagementPanel.studentMap;
        
        if(!studentmap.isEmpty()) {
            CourseEnrollmentPanel cep = new CourseEnrollmentPanel();
            cep.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(this, "Please add stduent first");
        }
        
    }//GEN-LAST:event_CourseManageActionPerformed

    private void GradeManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeManageActionPerformed
        if(!isStudentCourseEmpty()) {
            GradeManagementPanel gmp = new GradeManagementPanel();
            gmp.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(this, "Please add student and course First");
        }
        
    }//GEN-LAST:event_GradeManageActionPerformed
 
   private boolean isStudentCourseEmpty() {
    // Check if there are no students or courses added
    boolean isStudentEmpty = StudentManagementPanel.studentMap.isEmpty();
    boolean isCourseEmpty = CourseEnrollmentPanel.courseEnrollments.isEmpty();
    
    // Return true if either students or courses are empty
    return isStudentEmpty || isCourseEmpty;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainPanel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CourseManage;
    private javax.swing.JButton GradeManage;
    private javax.swing.JLabel HomeTitle;
    private javax.swing.JButton StdManage;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel leftMenu;
    // End of variables declaration//GEN-END:variables
}
